
return {

	fg                   = "#FFFADE",
	bg                   = "#060606",
	second_bg            = "#252525",

	dark                 = "#252525",
	popup_back           = "#2D2D30",
	cursor_fg            = "#515052",
	context              = "#606060",
	cursor_bg            = "#AEAFAD",
	accent               = "#BBBBBB",
	diff_add             = "#587C0C",
	diff_change          = "#0C7D9D",
	cl_bg                = "#178C94",
	diff_text            = "#265478",
	line_fg              = "#444444",
	line_bg              = "#0C0C0C",
	gutter_bg            = "#282C34",
	non_text             = "#373C45",
	selection_bg         = "#C6C6C6",
	selection_fg         = "#21252D",
	vsplit_fg            = "#CCCCCC",
	vsplit_bg            = "#21252D",
	visual_select_bg     = "#00005D",
	Visual               = "#2B2F31",

	red5                 = "#5D0000",
	red4                 = "#94151B",
	red3                 = "#FF5050",
	red2                 = "#F44747",
	red1                 = "#FC2929",
	red                  = "#FF0000",

	green3               = "#B5CEA8",
	green2               = "#50C16E",
	green1               = "#44B273",
	green                = "#00FF00",

	blue2                = "#9CDCFE",
	blue1                = "#4FC1FF",
	blue                 = "#0000FF",

	black3				 = "#0F0F0F",
	black2        		 = "#141414",
	black1        		 = "#090909",
	black         		 = "#000000",

	white         		 = "#FFFFFF",

	gray7                = "#CCCCCC",
	gray6                = "#C8C9C1",
	gray5                = "#9D9797",
	gray4                = "#8C8C8C",
	gray3                = "#808080",
	gray1                = "#3E3E3E",
	gray                 = "#21252D",

	orange6              = "#2F2905",
	orange5              = "#FFEE99",
	orange4              = "#613214",
	orange3              = "#ED722E",
	orange2              = "#E25600",
	orange1              = "#FF8800",
	orange               = "#FF8000",

	purple4              = "#D68EB2",
	purple3              = "#D16D9E",
	purple2              = "#D16BB7",
	purple               = "#8C00BF",

	cyan6                = "#1D918B",
	cyan5                = "#47A8A1",
	cyan3                = "#00BFA4",
	cyan                 = "#00FFFF",

	Cursor               = "#FFFF00",

	StorageClass         = "#F92672",
	MatchParenFG         = "#FFFADE",
	MatchParenBG         = "#1D918B",

	Define               = "#D68EB2",
	Braces               = "#8E24FF",
	BoxProp              = "#FF80FF",
	Definition           = "#FFCC66",
	Statement            = "#00DFFF",
	Block                = "#FC2929",
	Access               = "#FC2929",
	Structure            = "#FC2929",
	Typedef              = "#5AD1AA",
	Conditional          = "#50C16E",
	Repeat               = "#E30022",
	Error                = "#FF0000",
	ErrorMsg             = "#FF3939 ",
	Namespace            = "#FFFFFF",
	Operator             = "#F92672",
	Variable             = "#00BFA4",
	Property	         = "#00CC99",
	Boolean              = "#01A0F5",
	FlexibleBoxAttr      = "#00557F",
	Color                = "#FF557F",
	TagName              = "#00CC99",
	GeneratorExpressions = "#FF1111",
	KWuse_mangled_mesa   = "#FFFADE",
	Include              = "#F92672",
	PreProc              = "#F92672",
	String               = "#CF5C36",

	Function             = "#FFFFFF",
	KeywordFunction      = "#018ED5",
	Type                 = "#1D918B",
	Keyword              = "#E30022",
	KeywordReturn        = "#FC2929",
	KeywordOperator      = "#F92672",
	KeywordMatch         = "#FF0000",

	Parameter            = "#7FBEEB",
	Comment              = "#5C4D4D",
	Exception            = "#D68EB2",
	Number               = "#FFCC66",
	Method               = "#8877B1",
	Constructor          = "#01A0F5",
	FuncBuiltin          = "#00BFFF",
	Warning              = "#FBB13C",
	Note                 = "#FBB13C",
	Tag                  = "#178C94",
	TagAttribute         = "#00CC99",
	Annotation           = "#CC5500",
	Attribute            = "#E97451",
	Character            = "#50C16E",
	ConstBuiltin         = "#BD33A4",
	ConstMacro           = "#702963",
	Macro                = "#D68EB2",
	Constant             = "#FFFADE",
	Field                = "#05d2dd",
	Float                = "#D68EB2",
	FuncMacro            = "#006B3C",
	Label                = "#888888",
	Literal              = "#E30022",
	PunctBracket         = "#A3C1AD",
	PunctDelimiter       = "#C19A6B",
	PunctSpecial         = "#78866B",
	StringEscape         = "#FF0800",
	StringRegex          = "#FF0800",
	Strong               = "#E4717A",
	Symbol               = "#592720",
	TagDelimiter         = "#00CC99",
	Text                 = "#FFFF99",
	QueryLinterError     = "#EB4C42",
	Title                = "#FFFF99",
	TypeBuiltin          = "#FC2929",
	URI                  = "#B31B1B",
	VariableBuiltin      = "#99BADD",
	ParameterReference   = "#9CDCFE",
	KWproject            = "#F92672",
	KWvariable_watch     = "#00BFA4",
	Arguments            = "#1D918B",
	Command              = "#FFFFFF",
	UIProp               = "#E4717A",
	Identifier           = "#FFFADE",
	Ignore               = "#CCCCCC",
	SearchFG             = "#060606",
	SearchBg             = "#E25600",
	TodoFG               = "#FFFFFF",
	TodoBG               = "#3B3B1D",
	TableBlock           = "#FFCC66",

	markdownH                  = "#1D918B",
	markdownId                 = "#D16BB7",
	markdownUrl                = "#D16BB7",
	markdownRule               = "#BBBBBB",
	markdownBold               = "#CCCCCC",
	markdownCode               = "#ED722E",
	markdownItalic             = "#CCCCCC",
	markdownCodeBlock          = "#ED722E",
	markdownCodeError          = "#FF5050",
	markdownLinkText           = "#1D918B",
	markdownListMarker         = "#FC2929",
	markdownCodeSpecial        = "#E25600",
	markdownCodeDelimiter      = "#44B273",
	markdownBlockquote         = "#BBBBBB",
	markdownIdDeclaration      = "#1D918B",
	markdownIdDelimiter        = "#C8C9C1",
	markdownLinkDelimiter      = "#C8C9C1",
	markdownHeadingRule        = "#BBBBBB",
	markdownHeadingDelimiter   = "#1D918B",
	markdownUrlTitleDelimiter  = "#00BFA4",
	markdownOrderedListMarker  = "#FC2929",

	BufferCurrent              = "#141414",
	BufferCurrentMod           = "#FFCC66",
	BufferCurrentSign          = "#4FC1FF",
	BufferCurrentTarget        = "#FC2929",
	BufferInactive             = "#808080",
	BufferInactiveIndex        = "#808080",
	BufferInactiveMod          = "#FFCC66",
	BufferInactiveSign         = "#808080",
	BufferInactiveTarget       = "#FC2929",
	BufferLineFill             = "#141414",
	BufferVisibleMod           = "#FFCC66",
	BufferVisibleSign          = "#808080",
	BufferVisibleTarget        = "#FC2929",
	BuffNumbersBG              = "#141414",
	BuffNumbersFG              = "#FF0000",

	DiagnosticHint             = "#4FC1FF",
	DiagnosticError            = "#F44747",
	DiagnosticInfo             = "#FFCC66",
	DiagnosticWarn             = "#FF8800",
	DiagnosticFloatingError    = "#F44747",
	DiagnosticFloatingHint     = "#4FC1FF",
	DiagnosticFloatingInfo     = "#FFCC66",
	DiagnosticFloatingWarn     = "#FF8800",
	DiagnosticSignError        = "#F44747",
	DiagnosticSignHint         = "#4FC1FF",
	DiagnosticSignInfo         = "#FFCC66",
	DiagnosticSignWarn         = "#FF8800",
	DiagnosticVirtualTextError = "#840000",
	DiagnosticVirtualTextInfo  = "#2F2905",
	DiagnosticVirtualTextHint  = "#3E3E3E",
	DiagnosticVirtualTextWarn  = "#2F2905",

	FidgetTitle                = "#0c494a",
	FidgetTask                 = "#093536",

	FlutterWidgetGuides        = "#8C8C8C",

	GitAddFG                   = "#44B273",
	GitAddBG                   = "#060606",
	GitChangeFG                = "#967B11",
	GitChangeBG                = "#060606",
	GitDeleteFG                = "#FF0000",
	GitDeleteBG                = "#060606",

	IndentBlanklineChar        = "#fff000",
	IndentBlanklineContextChar = "#888888",
	IndentBlanklineSpaceChar   = "#126b70",
	IndentBlanklineIndent1     = "#1d1d26",
	IndentBlanklineIndent2     = "#17171e",
	IndentBlanklineIndent3     = "#1a171e",
	IndentBlanklineIndent4     = "#151d1c",
	IndentBlanklineIndent5     = "#111d13",
	IndentBlanklineIndent6     = "#1c1d15",
	IndentBlanklineIndent7     = "#1d0f12",
	IndentBlanklineIndent8     = "#1d0c19",

	IndentGuidesEven           = "#FFFADE",
	IndentGuidesOdd            = "#CCCCCC",

	LspSagaLightBulb           = "#44B273",

	NvimTreeCursorLineFG       = "#000000",
	NvimTreeCursorLinebG       = "#47A8A1",
	NvimTreeExecFile           = "#44B273",
	NvimTreeFolderIcon         = "#1D918B",
	NvimTreeFolderName         = "#1D918B",
	NvimTreeGitDeleted         = "#94151B",
	NvimTreeGitDirty           = "#587C0C",
	NvimTreeGitMerge           = "#0C7D9D",
	NvimTreeGitNew             = "#587C0C",
	NvimTreeGitRenamed         = "#0C7D9D",
	NvimTreeGitStaged          = "#587C0C",
	NvimTreeImageFile          = "#D16BB7",
	NvimTreeIndentMarker       = "#808080",
	NvimTreeNormal             = "#BBBBBB",
	NvimTreeRootFolder         = "#808080",
	NvimTreeSpecialFile        = "#E25600",
	NvimTreeSymlink            = "#00BFA4",
	NvimTreeVertSplit          = "#3E3E3E",
	NvimTreeOpenedFolderName   = "#1D918B",

	TelescopeBorder            = "#808080",
	TelescopeMatching          = "#FF8000",
	TelescopePromptPrefix      = "#00DFFF",
	TelescopeSelectionFG       = "#FFFFFF",
	TelescopeSelectionBG       = "#21252D",

	TroubleFileFG              = "#000000",
	TroubleFileBG              = "#C8C9C1",
	TroubleFoldIcon            = "#FF0000",
	TroubleTextError           = "#FF5050",
	TroubleNormal              = "#FFFFFF",
	TroubleLocation            = "#00FFFF",
	TroubleIndent              = "#FFFFFF",
	TroubleSignError           = "#FF0000",
	TroubleCount               = "#FF0000",
	TroubleCode                = "#444400",
}

