local M = {}

---@type COLORS
M.colors = {

	fg               = "#FFFADE",
	bg               = "#060606",
	second_bg        = "#252525",
	Border           = "#808080",
	GhostText        = "#404040",

	-- Completion Menu
	CmpMenu          = "#C8C9C1",
	CmpItemLabel     = "#00BFA4",
	CmpItemLabelDesc = "#373C45",
	CmpDoc           = "#FFFADE",


	-- GUI

	CurSearch                 = "#FF0000",
	Cursor                    = "#FFFF00",
	CursorLine                = "#141414",
	CursorLineNrBG            = "#178C94",
	CursorLineNrFG            = "#000000",
	Delimiter                 = "#CCCCCC",
	DiffAdd                   = "#44B273",
	DiffChange                = "#E25600",
	DiffDelete                = "#FC2929",
	DiffFile                  = "#D16BB7",
	DiffText                  = "#1D918B",
	FoldedBG                  = "#141414",
	FoldedFG                  = "#178C94",
	LineNr                    = "#444444",
	MoreMsg                   = "#E25600",
	Pmenu                     = "#808080",
	PmenuSelBG                = "#1D918B",
	PmenuSelFG                = "#000000",
	PmenuThumb                = "#1D918B",
	QuickFixLine              = "#3E3E3E",
	StatusLine                = "#141414",
	StatusLineNCBG            = "#21252D",
	StatusLineNCFG            = "#CCCCCC",
	StatusLineSeparator       = "#252525",
	StatusLineTermBG          = "#21252D",
	StatusLineTermFG          = "#47A8A1",
	StatusLineTermNCBG        = "#21252D",
	StatusLineTermNCFG        = "#CCCCCC",
	SubstituteBG              = "#C8C9C1",
	SubstituteFG              = "#613214",
	Visual                    = "#21252D",
	VisualNOSBG               = "#C6C6C6",
	VisualNOSFG               = "#21252D",
	WarningMsgBG              = "#ED722E",
	WarningMsgFG              = "#21252D",
	Whitespace                = "#212520",
	lCursorBG                 = "#AEAFAD",
	lCursorFG                 = "#515052",

	-- LANGUAGES
	Access                    = "#FC2929",
	Annotation                = "#CC5500",
	Arguments                 = "#1D918B",
	Attribute                 = "#E97451",
	Block                     = "#FC2929",
	BoxProp                   = "#FF80FF",
	Braces                    = "#8E24FF",
	Color                     = "#FF557F",
	Command                   = "#FFFFFF",
	Comment                   = "#5C4D4D",
	ConstBuiltin              = "#BD33A4",
	ConstMacro                = "#702963",
	Constant                  = "#FFCC66",
	Constructor               = "#01A0F5",
	Definition                = "#FFCC66",
	Error                     = "#FF0000",
	ErrorMsg                  = "#FF3939",
	Field                     = "#05d2dd",
	FlexibleBoxAttr           = "#00557F",
	FuncBuiltin               = "#00BFFF",
	FuncMacro                 = "#006B3C",
	Function                  = "#FFFFFF",
	Identifier                = "#FFFADE",
	KWproject                 = "#F92672",
	KWuse_mangled_mesa        = "#FFFADE",
	KWvariable_watch          = "#00BFA4",
	KeywordFunction           = "#018ED5",
	KeywordOperator           = "#F92672",
	KeywordReturn             = "#FC2929",
	Literal                   = "#E30022",
	MatchParenBG              = "#1D918B",
	MatchParenFG              = "#FFFADE",
	Method                    = "#8877B1",
	Namespace                 = "#FFFFFF",
	NonText                   = "#373C45",
	Note                      = "#FBB13C",
	Operator                  = "#F92672",
	Parameter                 = "#7FBEEB",
	ParameterReference        = "#9CDCFE",
	PreProc                   = "#F92672",
	Property                  = "#00CC99",
	PunctBracket              = "#A3C1AD",
	PunctDelimiter            = "#C19A6B",
	PunctSpecial              = "#78866B",
	QueryLinterError          = "#EB4C42",
	Question                  = "#21252D",
	SearchBg                  = "#E25600",
	SearchFG                  = "#060606",
	Special                   = "#ED722E",
	SpecialKey                = "#CCCCCC",
	SpellBad                  = "#FC2929",
	SpellCap                  = "#E25600",
	SpellLocal                = "#44B273",
	SpellRare                 = "#D16BB7",
	Statement                 = "#00DFFF",
	String                    = "#CF5C36",
	StringRegex               = "#FF0800",
	Strong                    = "#E4717A",
	Symbol                    = "#592720",
	TabLineFG                 = "#B3B3B3",
	TabLineBG                 = "#141414",
	TabLineSel                = "#072B2C",
	TabLineCurrentWin         = "#7AA6ff",
	TableBlock                = "#FFCC66",
	Tag                       = "#00CC99",
	Text                      = "#FFFF99",
	TodoBG                    = "#3B3B1D",
	TodoFG                    = "#FFFFFF",
	Type                      = "#1D918B",
	TypeBuiltin               = "#FC2929",
	URI                       = "#B31B1B",
	Variable                  = "#00BFA4",
	VariableBuiltin           = "#99BADD",
	Warning                   = "#FBB13C",

	-- PLUGINS

	-- Buffer: github.com/akinsho/nvim-bufferline.lua
	BufferCloseButtonSelected = "#141414",
	BufferCurrentBg           = "#141414",
	BufferCurrentFg           = "#b3b3b3",
	BufferCurrentMod          = "#FFCC66",
	BufferCurrentSign         = "#4FC1FF",
	BufferCurrentTarget       = "#FC2929",
	BufferInactive            = "#808080",
	BufferInactiveIndex       = "#808080",
	BufferInactiveMod         = "#FFCC66",
	BufferInactiveSign        = "#808080",
	BufferInactiveTarget      = "#FC2929",
	BufferIndicatorSelected   = "#141414",
	BufferLineFill            = "#141414",
	BufferVisibleMod          = "#FFCC66",
	BufferVisibleSign         = "#808080",
	BufferVisibleTarget       = "#FC2929",
	BuffNumbers               = "#141414",
	BufferSelected            = "#141414",

	DashboardCenter            = "#D16BB7",
	DashboardFooter            = "#00BFA4",
	DashboardHeader            = "#1D918B",

	debugBreakpoint            = "#FC2929",
	debugPc                    = "#00BFA4",

	DiagnosticError            = "#862727",
	DiagnosticHint             = "#255c79",
	DiagnosticInfo             = "#587C0C",
	DiagnosticWarn             = "#846a00",

	DiffViewNormal             = "#808080",
	DiffviewFilePanelDeletion  = "#94151B",
	DiffviewFilePanelInsertion = "#587C0C",
	DiffviewStatusAdded        = "#587C0C",
	DiffviewStatusDeleted      = "#94151B",
	DiffviewStatusModified     = "#0C7D9D",
	DiffviewStatusRenamed      = "#0C7D9D",

	FidgetTitle                = "#147e7e",
	FidgetTask                 = "#106161",

	FlutterWidgetGuides        = "#8C8C8C",

	GitAdd                     = "#215637",
	GitChange                  = "#5f4d0b",
	GitDelete                  = "#FF0000",
	GitUntracked               = "#215637",
	GitBG                      = "#141414",
	GitAddPreviewFG            = "#00ff04",
	GitAddPreviewBG            = "#002201",
	GitDeletePreviewFG         = "#FF0000",
	GitDeletePreviewBG         = "#240001",

	GitGutterAddFG             = "#44B273",
	GitGutterChangeFG          = "#967B11",
	GitGutterDeleteFG          = "#FF0000",
	GitGutterBG                = "#060606",

	IblIndent                  = "#111111",
	IblScope                   = "#777777",
	IblSpaceChar               = "#126b70",

	IndentGuidesEven           = "#FFFADE",
	IndentGuidesOdd            = "#CCCCCC",

	LspSagaLightBulb           = "#44B273",

	NvimTreeCursorLineFG       = "#000000",
	NvimTreeGitDeleted         = "#94151B",
	NvimTreeGitMerge           = "#0C7D9D",
	NvimTreeGitRenamed         = "#0C7D9D",
	NvimTreeCursorLinebG       = "#47A8A1",
	NvimTreeSymlink            = "#00BFA4",
	NvimTreeFolder             = "#1D918B",
	NvimTreeOpenedFolderName   = "#1D918B",
	NvimTreeExecFile           = "#44B273",
	NvimTreeGitDirty           = "#587C0C",
	NvimTreeGitNew             = "#587C0C",
	NvimTreeGitStaged          = "#587C0C",
	NvimTreeImageFile          = "#D16BB7",
	NvimTreeIndentMarker       = "#808080",
	NvimTreeNormal             = "#BBBBBB",
	NvimTreeSpecialFile        = "#E25600",
	NvimTreeVertSplit          = "#3E3E3E",

	NeoTreeIndentMarker        = "#808080",
	NeoTreeExpander            = "#1D918B",
	NeoTreeFileIcon            = "#587C0C",
	NeoTreeModified            = "#1D918B",
	NeoTreeFileName            = "#DDDDDD",

	NeogitBranch               = "#D16D9E",
	NeogitDiffAdd              = "#587C0C",
	NeogitDiffContext          = "#BBBBBB",
	NeogitDiffDelete           = "#94151B",
	NeogitHunkHeader           = "#BBBBBB",
	NeogitRemote               = "#D16BB7",

	-- snacks.nvim: github.com/folke/snacks.nvim
	SnacksIndent               = "#111111",
	SnacksIndentChunk          = "#888888",
	SnacksIndentScope          = "#777777",
	SnacksDashboardNormal      = "#1D918B",
	SnacksDashboardDesc        = "#EEEEEE",
	SnacksDashboardDir         = "#999999",

	TabSelectedFG              = "#FFFFFF",
	TabSelectedBG              = "#141414",
	TabFG                      = "#FFFFFF",
	TabBG                      = "#141414",

	TelescopeMatching          = "#FF8000",
	TelescopePromptPrefix      = "#00DFFF",
	TelescopeSelectionFG       = "#FFFFFF",
	TelescopeSelectionBG       = "#21252D",

	TroubleFile                = "#FFFFFF",
	TroubleSignError           = "#FF0000",
	TroubleTextError           = "#FF5050",
	TroubleSignWarn            = "#444400",
	TroubleCountBG             = "#404040",
	TroubleSignHint            = "#626262",
	TroubleNormal              = "#808080",

	NavicIconsBoolean          = "#015c8a",
	NavicIconsEnum             = "#168888",
	NavicIconsMethod           = "#73538c",
	NavicIconsModule           = "#8d7138",
	NavicIconsNamespace        = "#FFFFFF",
	NavicIconsFile             = "#acacac",
	NavicText                  = "#666666",
	NavicIconsNull             = "#8c0015",

	NoiceCmdlineSearch         = "#E25600",
}

return M
