---@type AbstractCsPalette
return {
    main            = "#7aa2f7",
    bg              = "#1a1b26",
    bg_2            = "#232433",
    bg_highlight    = "#3b3d4d",
    fg              = "#c0caf5",
    comment         = "#565f89",
    match           = "#90bcff",
    special         = "#b5d9ff",
    warn            = "#ba9056",
    border          = "#9ab1dc",
    highlight       = "#c5d4ff",
    indent          = "#2B2B2B",
    indent_scope    = "#777777",
    sucess          = "#2a6d45",
    error           = "#f7768E",

    -- Language Syntax
    sntx_comment    = "#565f89",
    sntx_constant   = "#b5d9ff",
    sntx_delimiter  = "#c0caf5",
    sntx_variable   = "#ffffff",
    sntx_function   = "#7aa2f7",
    sntx_identifier = "#7aa2f7",
    sntx_keyword    = "#90bcff",
    sntx_statement  = "#90bcff",
    sntx_operator   = "#b5d9ff",
    sntx_preproc    = "#ba9056",
    sntx_special    = "#b5d9ff",
    sntx_string     = "#b5d9ff",
    sntx_type       = "#c5d4ff",
}
