local M = {}

---Create highlight groups from a palette
---@param c AbstractCsPalette
---@return table<string, vim.api.keyset.highlight>
function M.groups(c)
    return {
        -- Basic UI
        ColorColumn                 = { bg = c.bg },
        Conceal                     = { fg = c.comment },
        CurSearch                   = { link = 'IncSearch' },
        Cursor                      = { reverse = true },
        CursorColumn                = { bg = c.bg_2 },
        CursorIM                    = { link = 'Cursor' },
        CursorLine                  = { bg = c.bg_2 },
        CursorLineNr                = { fg = c.fg, bg = c.bg_2, bold = true },
        DiffAdd                     = { fg = c.sucess, bg = c.bg },
        DiffChange                  = { fg = c.match, bg = c.bg },
        DiffDelete                  = { fg = c.error, bg = c.bg },
        DiffText                    = { fg = c.fg, bg = c.bg_highlight },
        Directory                   = { fg = c.main },
        EndOfBuffer                 = { fg = c.bg },
        ErrorMsg                    = { fg = c.error, bold = true },
        FloatBorder                 = { link = "Border" },
        FloatTitle                  = { fg = c.main, bg = c.bg },
        FoldColumn                  = { fg = c.comment, bg = c.bg },
        Folded                      = { fg = c.comment, bg = c.bg },
        IncSearch                   = { fg = c.bg, bg = c.match },
        LineNr                      = { fg = c.comment, bg = c.bg },
        LineNrAbove                 = { link = 'LineNr' },
        LineNrBelow                 = { link = 'LineNr' },
        MatchParen                  = { fg = c.match, bg = c.bg_2, bold = true },
        ModeMsg                     = { fg = c.warn },
        MoreMsg                     = { fg = c.warn },
        MsgArea                     = { fg = c.fg, bg = c.bg },
        NonText                     = { fg = c.bg_highlight },
        Normal                      = { fg = c.fg, bg = c.bg },
        NormalFloat                 = { link = "Normal" },
        NormalNC                    = { link = "Normal" },
        NormalSB                    = { link = "Normal" },
        Pmenu                       = { fg = c.fg, bg = c.bg },
        PmenuMatch                  = { fg = c.main, bg = c.bg },
        PmenuMatchSel               = { fg = c.bg, bg = c.match },
        PmenuSbar                   = { bg = c.bg },
        PmenuSel                    = { fg = c.bg, bg = c.main },
        PmenuThumb                  = { bg = c.bg_highlight },
        Question                    = { fg = c.warn },
        QuickFixLine                = { fg = c.main, bg = c.bg },
        Search                      = { fg = c.bg, bg = c.main },
        SignColumn                  = { fg = c.comment, bg = c.bg },
        SignColumnSB                = { link = 'SignColumn' },
        SpecialKey                  = { fg = c.special },
        SpellBad                    = { undercurl = true, sp = c.error },
        SpellCap                    = { undercurl = true, sp = c.main },
        SpellLocal                  = { undercurl = true, sp = c.sucess },
        SpellRare                   = { undercurl = true, sp = c.match },
        StatusLine                  = { fg = c.fg, bg = c.bg_2 },
        StatusLineNC                = { fg = c.comment, bg = c.bg_2 },
        Substitute                  = { fg = c.bg, bg = c.main },
        TabLine                     = { fg = c.fg, bg = c.bg },
        TabLineFill                 = { fg = c.fg, bg = c.bg },
        TabLineSel                  = { fg = c.bg, bg = c.main },
        Title                       = { fg = c.main, bold = true },
        VertSplit                   = { fg = c.fg },
        Visual                      = { bg = c.bg_highlight },
        VisualNOS                   = { bg = c.bg_highlight },
        WarningMsg                  = { fg = c.warn },
        Whitespace                  = { fg = c.bg_highlight },
        WildMenu                    = { fg = c.bg, bg = c.main },
        WinBar                      = { fg = c.indent_scope, bg = c.bg_2 },
        WinBarNC                    = { fg = c.comment, bg = c.bg },
        WinSeparator                = { fg = c.fg },
        lCursor                     = { link = 'Cursor' },
        -- Generic syntax
        Bold                        = { bold = true },
        Character                   = { fg = c.warn },
        Comment                     = { fg = c.comment, italic = true },
        Constant                    = { fg = c.highlight },
        Debug                       = { fg = c.error },
        Delimiter                   = { fg = c.fg },
        Error                       = { fg = c.error, bg = c.bg },
        Function                    = { fg = c.main },
        Identifier                  = { fg = c.main },
        Italic                      = { italic = true },
        Keyword                     = { fg = c.match },
        Operator                    = { fg = c.fg },
        PreProc                     = { fg = c.match },
        Special                     = { fg = c.special },
        Statement                   = { fg = c.match },
        String                      = { fg = c.highlight },
        Todo                        = { fg = c.match, bg = c.bg },
        Type                        = { fg = c.main },
        Underlined                  = { underline = true },
        debugBreakpoint             = { fg = c.bg, bg = c.error },
        debugPC                     = { fg = c.bg, bg = c.sucess },
        dosIniLabel                 = { fg = c.match },
        helpCommand                 = { fg = c.main },
        htmlH1                      = { fg = c.main, bold = true },
        htmlH2                      = { fg = c.match, bold = true },
        qfFileName                  = { fg = c.main },
        qfLineNr                    = { fg = c.warn },
        -- LSP references
        LspCodeLens                 = { fg = c.comment },
        LspInfoBorder               = { link = "Border" },
        LspInlayHint                = { fg = c.comment, bg = c.bg },
        LspReferenceRead            = { bg = c.bg },
        LspReferenceText            = { bg = c.bg },
        LspReferenceWrite           = { bg = c.bg },
        LspSignatureActiveParameter = { fg = c.main },
        -- Diagnostics
        DiagnosticError             = { fg = c.error },
        DiagnosticHint              = { fg = c.special },
        DiagnosticInfo              = { fg = c.main },
        DiagnosticUnderlineError    = { undercurl = true, sp = c.error },
        DiagnosticUnderlineHint     = { undercurl = true, sp = c.special },
        DiagnosticUnderlineInfo     = { undercurl = true, sp = c.main },
        DiagnosticUnderlineWarn     = { undercurl = true, sp = c.warn },
        DiagnosticUnnecessary       = { fg = c.comment },
        DiagnosticVirtualTextError  = { fg = c.error },
        DiagnosticVirtualTextHint   = { fg = c.special },
        DiagnosticVirtualTextInfo   = { fg = c.main },
        DiagnosticVirtualTextWarn   = { fg = c.warn },
        DiagnosticWarn              = { fg = c.warn },
        -- Health output
        healthError                 = { fg = c.error },
        healthSuccess               = { fg = c.sucess },
        healthWarning               = { fg = c.warn },
        -- diff
        diffAdded                   = { fg = c.sucess },
        diffChanged                 = { fg = c.match },
        diffFile                    = { fg = c.main },
        diffIndexLine               = { fg = c.main },
        diffLine                    = { fg = c.warn },
        diffNewFile                 = { fg = c.sucess },
        diffOldFile                 = { fg = c.error },
        diffRemoved                 = { fg = c.error },
        helpExample                 = { fg = c.warn },


        -- === Customs === --


        Border      = { fg = c.border, bg = c.bg },
        Indent      = { fg = c.indent },
        IndentScope = { fg = c.indent_scope },


        -- === Treesitter === --
        ["@attribute"]                  = { link = "Macro" },
        ["@attribute.builtin"]          = { link = "Special" },
        ["@boolean"]                    = { link = "Boolean" },
        ["@character"]                  = { link = "Character" },
        ["@character.special"]          = { link = "SpecialChar" },
        ["@comment"]                    = { link = "Comment" },
        ["@comment.error"]              = { link = "DiagnosticError" },
        ["@comment.note"]               = { link = "DiagnosticInfo" },
        ["@comment.todo"]               = { link = "Todo" },
        ["@comment.warning"]            = { link = "DiagnosticWarn" },
        ["@conceal"]                    = { link = "Conceal" },
        ["@constant"]                   = { link = "Constant" },
        ["@constant.builtin"]           = { link = "Special" },
        ["@constructor"]                = { link = "Special" },
        ["@diff.delta"]                 = { link = "Changed" },
        ["@diff.minus"]                 = { link = "Removed" },
        ["@diff.plus"]                  = { link = "Added" },
        ["@function"]                   = { link = "Function" },
        ["@function.builtin"]           = { link = "Special" },
        ["@keyword"]                    = { link = "Keyword" },
        ["@label"]                      = { link = "Label" },
        ["@lsp.mod.deprecated"]         = { link = "DiagnosticDeprecated" },
        ["@lsp.type.class"]             = { link = "@type" },
        ["@lsp.type.comment"]           = { link = "@comment" },
        ["@lsp.type.decorator"]         = { link = "@attribute" },
        ["@lsp.type.enum"]              = { link = "@type" },
        ["@lsp.type.enumMember"]        = { link = "@constant" },
        ["@lsp.type.event"]             = { link = "@type" },
        ["@lsp.type.function"]          = { link = "@function" },
        ["@lsp.type.interface"]         = { link = "@type" },
        ["@lsp.type.keyword"]           = { link = "@keyword" },
        ["@lsp.type.macro"]             = { link = "@constant.macro" },
        ["@lsp.type.method"]            = { link = "@function.method" },
        ["@lsp.type.modifier"]          = { link = "@type.qualifier" },
        ["@lsp.type.namespace"]         = { link = "@module" },
        ["@lsp.type.number"]            = { link = "@number" },
        ["@lsp.type.operator"]          = { link = "@operator" },
        ["@lsp.type.parameter"]         = { link = "@variable.parameter" },
        ["@lsp.type.property"]          = { link = "@property" },
        ["@lsp.type.regexp"]            = { link = "@string.regexp" },
        ["@lsp.type.string"]            = { link = "@string" },
        ["@lsp.type.struct"]            = { link = "@type" },
        ["@lsp.type.type"]              = { link = "@type" },
        ["@lsp.type.typeParameter"]     = { link = "@type.definition" },
        ["@lsp.type.variable"]          = { link = "@variable" },
        ["@markup"]                     = { link = "Special" },
        ["@markup.heading"]             = { link = "Title" },
        ["@markup.italic"]              = { italic = true },
        ["@markup.link"]                = { link = "Underline" },
        ["@markup.strikethrough"]       = { strikethrough = true },
        ["@markup.strong"]              = { bold = true },
        ["@markup.underline"]           = { underline = true },
        ["@module"]                     = { link = "Structure" },
        ["@module.builtin"]             = { link = "Special" },
        ["@number"]                     = { link = "Number" },
        ["@number.float"]               = { link = "Float" },
        ["@operator"]                   = { link = "Operator" },
        ["@property"]                   = { link = "Identifier" },
        ["@punctuation"]                = { link = "Delimiter" },
        ["@punctuation.specia"]         = { link = "Special" },
        ["@string"]                     = { link = "String" },
        ["@string.escape"]              = { link = "@string.special" },
        ["@string.regexp"]              = { link = "@string.special" },
        ["@string.special"]             = { link = "SpecialChar" },
        ["@string.special.url"]         = { link = "Underline" },
        ["@tag"]                        = { link = "Tag" },
        ["@tag.builtin"]                = { link = "Special" },
        ["@type"]                       = { link = "Type" },
        ["@type.builtin"]               = { link = "Special" },
        ["@variable.builtin"]           = { link = "Special" },
        ["@variable.parameter"]         = { italic = true },
        ["@variable.parameter.builtin"] = { link = "Special" },


        -- === Plugins === --


        -- Blink.cmp: https://github.com/Saghen/blink.cmp
        BlinkCmpMenu       = { bg = c.bg },       --  The completion menu window
        BlinkCmpDocBorder  = { link = "Border" },
        BlinkCmpMenuBorder = { link = "Border" }, --  The completion menu window border
        BlinkCmpLabelMatch = { fg = c.match },    --  Label of the completion item when it matches the query
        -- BlinkCmpLabelDescription = { fg = colors.CmpItemLabelDesc }, --  NonText	Label description of the completion item
        -- BlinkCmpDoc              = { fg = colors.CmpDoc },

        -- Snacks.nvim: github.com/folke/snacks.nvim
        SnacksIndent       = { link = "Indent" },
        SnacksIndentScope  = { link = "IndentScope" },

        -- Telescope: github.com/nvim-telescope/telescope.nvim
        TelescopeBorder    = { link = "Border" },
        TelescopeMatching  = { fg = c.match },
        -- TelescopePromptPrefix = { fg = colors.TelescopePromptPrefix },
        -- TelescopeSelection    = { fg = colors.TelescopeSelectionFG, bg = colors.TelescopeSelectionBG },

        -- Trouble: https://github.com/folke/trouble.nvim
        TroubleCode        = { fg = c.error },
        TroubleCount       = { fg = c.fg, bg = c.bg_highlight },
        TroubleIndent      = { fg = c.fg }, -- indent color
        TroublePos         = { fg = c.fg }, -- background color of unfocused trouble window
        TroubleSignHint    = { fg = c.fg, bg = c.bg_highlight },

        -- Others
        GitSignsAdd        = { fg = c.sucess },
        GitSignsChange     = { fg = c.warn },
        GitSignsDelete     = { fg = c.error },
        GitSignsUntracked  = { fg = c.fg },
    }
end

return M
