---Palette table used for highlighting
---@class AbstractCsPalette
---@field main string         -- main colour
---@field fg string           -- main foreground
---@field bg string           -- main background
---@field bg_2 string         -- darker background used for sidebars
---@field bg_highlight string -- highlight background
---@field highlight string    -- lighter foreground
---@field comment string      -- comments and secondary text
---@field match string
---@field special string
---@field warn string
---@field border string
---@field indent string
---@field indent_scope string
---@field sucess string
---@field error string
-- virtual texts
---@field virtual_error string
---@field virtual_hint string
---@field virtual_info string
---@field virtual_warn string
-- language syntax
---@field sntx_comment string
---@field sntx_constant string
---@field sntx_delimiter string
---@field sntx_function string
---@field sntx_identifier string
---@field sntx_keyword string
---@field sntx_operator string
---@field sntx_preproc string
---@field sntx_special string
---@field sntx_statement string
---@field sntx_string string
---@field sntx_type string
---@field sntx_variable string

---@class AbstractCsColorGroup
---@field highlights? table<string, vim.api.keyset.highlight> -- highlight overrides
---@field colors? AbstractCsPalette -- highlight's color overrides

---@class AbstractCsOptions
---@field name?  AbstractCsName
---@field global? AbstractCsColorGroup
---@field themes? table<AbstractCsName, AbstractCsColorGroup>
---@field theme_switched? boolean

---@alias AbstractCsName
---| "aqua"
---| "bluish"
---| "code"
---| "cold"
---| "dirtish"
---| "friend"
---| "midnight"
---| "nightish"
---| "redish"
---| "romantic"
