--- @class SetupOptions
--- @field theme? 'aqua'
--- @field custom_highlights? table<string, vim.api.keyset.highlight>

---@class COLORS
--- @field fg string
--- @field bg string
--- @field second_bg string
--- GUI ---
---@field CurSearch string
---@field Cursor string
---@field CursorLine string
---@field CursorLineNrBG string
---@field CursorLineNrFG string
---@field Delimiter string
---@field DiffAdd string
---@field DiffChange string
---@field DiffDelete string
---@field DiffFile string
---@field DiffText string
---@field FoldedBG string
---@field FoldedFG string
---@field LineNr string
---@field MoreMsg string
---@field Pmenu string
---@field PmenuSelBG string
---@field PmenuSelFG string
---@field PmenuThumb string
---@field QuickFixLine string
---@field StatusLine string
---@field StatusLineNCBG string
---@field StatusLineNCFG string
---@field StatusLineSeparator string
---@field StatusLineTermBG string
---@field StatusLineTermFG string
---@field StatusLineTermNCBG string
---@field StatusLineTermNCFG string
---@field SubstituteBG string
---@field SubstituteFG string
---@field Visual string
---@field VisualNOSBG string
---@field VisualNOSFG string
---@field WarningMsgBG string
---@field WarningMsgFG string
---@field Whitespace string
---@field lCursorBG string
---@field lCursorFG string
--- LANGUAGES ---
---@field Access string
---@field Annotation string
---@field Arguments string
---@field Attribute string
---@field Block string
---@field BoxProp string
---@field Braces string
---@field Color string
---@field Command string
---@field Comment string
---@field ConstBuiltin string
---@field ConstMacro string
---@field Constant string
---@field Constructor string
---@field Definition string
---@field Error string
---@field ErrorMsg string
---@field Field string
---@field FlexibleBoxAttr string
---@field FuncBuiltin string
---@field FuncMacro string
---@field Function string
---@field Identifier string
---@field KWproject string
---@field KWuse_mangled_mesa string
---@field KWvariable_watch string
---@field KeywordFunction string
---@field KeywordOperator string
---@field KeywordReturn string
---@field Literal string
---@field MatchParenBG string
---@field MatchParenFG string
---@field Method string
---@field Namespace string
---@field NonText string
---@field Note string
---@field Operator string
---@field Parameter string
---@field ParameterReference string
---@field PreProc string
---@field Property string
---@field PunctBracket string
---@field PunctDelimiter string
---@field PunctSpecial string
---@field QueryLinterError string
---@field Question string
---@field SearchBg string
---@field SearchFG string
---@field Special string
---@field SpecialKey string
---@field SpellBad string
---@field SpellCap string
---@field SpellLocal string
---@field SpellRare string
---@field Statement string
---@field String string
---@field StringRegex string
---@field Strong string
---@field Symbol string
---@field TabLineFG string
---@field TabLineBG string
---@field TabLineSel string
---@field TabLineCurrentWin string
---@field TableBlock string
---@field Tag string
---@field Text string
---@field TodoBG string
---@field TodoFG string
---@field Type string
---@field TypeBuiltin string
---@field URI string
---@field Variable string
---@field VariableBuiltin string
---@field Warning string
--- PLUGINS ---
---@field BufferCloseButtonSelected string
---@field BufferCurrentBg string
---@field BufferCurrentFg string
---@field BufferCurrentMod string
---@field BufferCurrentSign string
---@field BufferCurrentTarget string
---@field BufferInactive string
---@field BufferInactiveIndex string
---@field BufferInactiveMod string
---@field BufferInactiveSign string
---@field BufferInactiveTarget string
---@field BufferIndicatorSelected string
---@field BufferLineFill string
---@field BufferVisibleMod string
---@field BufferVisibleSign string
---@field BufferVisibleTarget string
---@field BuffNumbers string
---@field BufferSelected string
-- blink.cmp: github.com/Saghen/blink.cmp
---@field BlinkCmpMenu string
---@field BlinkCmpMenuBorder string
-- ---@field BlinkCmpMenuSelection string
-- ---@field BlinkCmpScrollBarThumb string
-- ---@field BlinkCmpScrollBarGutter string
-- ---@field BlinkCmpLabel string
-- ---@field BlinkCmpLabelDeprecated string
---@field BlinkCmpLabelMatch string
-- ---@field BlinkCmpLabelDetail string
---@field BlinkCmpLabelDescription string
-- ---@field BlinkCmpKind string
-- ---@field BlinkCmpSource string
-- ---@field BlinkCmpGhostText string
-- ---@field BlinkCmpDoc string
-- ---@field BlinkCmpDocBorder string
-- ---@field BlinkCmpDocSeparator string
-- ---@field BlinkCmpDocCursorLine string
-- ---@field BlinkCmpSignatureHelp string
-- ---@field BlinkCmpSignatureHelpBorder string
-- ---@field BlinkCmpSignatureHelpActiveParameter string
-- github.com/hrsh7th/nvim-cmp
---@field CmpDocumentation string
---@field CmpDocumentationBorder string
---@field CmpItemAbbrMatch string
---@field CmpItemMenu string
---@field CmpItemKindClass string
---@field CmpItemKindFunction string
---@field CmpItemKindKeyword string
---@field CmpItemKindText string
---@field DashboardCenter string
---@field DashboardFooter string
---@field DashboardHeader string
---@field debugBreakpoint string
---@field debugPc string
---@field DiagnosticHint string
---@field DiagnosticError string
---@field DiagnosticInfo string
---@field DiagnosticWarn string
---@field DiffViewNormal string
---@field DiffviewFilePanelDeletion string
---@field DiffviewFilePanelInsertion string
---@field DiffviewStatusAdded string
---@field DiffviewStatusDeleted string
---@field DiffviewStatusModified string
---@field DiffviewStatusRenamed string
---@field FidgetTitle string
---@field FidgetTask string
---@field FlutterWidgetGuides string
---@field GitAdd string
---@field GitChange string
---@field GitDelete string
---@field GitUntracked string
---@field GitBG string
---@field GitAddPreviewFG string
---@field GitAddPreviewBG string
---@field GitDeletePreviewFG string
---@field GitDeletePreviewBG string
---@field GitGutterAddFG string
---@field GitGutterBG string
---@field GitGutterChangeFG string
---@field GitGutterDeleteFG string
-- https://github.com/lukas-reineke/indent-blankline.nvim
---@field IblIndent string
---@field IblScope string
---@field IblSpaceChar string
---@field IndentGuidesEven string
---@field IndentGuidesOdd string
---@field LspSagaLightBulb string
---@field NvimTreeCursorLineFG string
---@field NvimTreeCursorLinebG string
---@field NvimTreeExecFile string
---@field NvimTreeFolder string
---@field NvimTreeGitDeleted string
---@field NvimTreeGitDirty string
---@field NvimTreeGitMerge string
---@field NvimTreeGitNew string
---@field NvimTreeGitRenamed string
---@field NvimTreeGitStaged string
---@field NvimTreeImageFile string
---@field NvimTreeIndentMarker string
---@field NvimTreeNormal string
---@field NvimTreeSpecialFile string
---@field NvimTreeSymlink string
---@field NvimTreeVertSplit string
---@field NvimTreeOpenedFolderName string
---@field NeoTreeIndentMarker string
---@field NeoTreeExpander string
---@field NeoTreeFileIcon string
---@field NeoTreeModified string
---@field NeoTreeFileName string
---@field NeogitBranch string
---@field NeogitDiffAdd string
---@field NeogitDiffContext string
---@field NeogitDiffDelete string
---@field NeogitHunkHeader string
---@field NeogitRemote string
-- snacks.nvim: github.com/folke/snacks.nvim
---@field SnacksIndentScope string
---@field SnacksIndentChunk string
---@field SnacksIndent string
---@field SnacksDashboardNormal string
---@field SnacksDashboardDesc string
---@field SnacksDashboardDir string
--
---@field TabSelectedFG string
---@field TabSelectedBG string
---@field TabFG string
---@field TabBG string
-- telescope.nvim: github.com/nvim-telescope/telescope.nvim
---@field TelescopeBorder string
---@field TelescopeMatching string
---@field TelescopePromptPrefix string
---@field TelescopeSelectionFG string
---@field TelescopeSelectionBG string
-- trouble.nvim: github.com/folke/trouble.nvim
---@field TroubleFile string
---@field TroubleTextError string
---@field TroubleNormal string
---@field TroubleSignError string
---@field TroubleSignHint string
---@field TroubleSignWarn string
-- https://github.com/SmiteshP/nvim-navic
---@field NavicIconsBoolean string
---@field NavicIconsEnum string
---@field NavicIconsFile string
---@field NavicIconsMethod string
---@field NavicIconsModule string
---@field NavicIconsNamespace string
---@field NavicIconsNull string
---@field NavicText string
-- https://github.com/folke/noice.nvim
---@field NoiceCmdlineSearch string
